
package com.cfn.app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessageSampleService", targetNamespace = "http://app.cfn.com/", wsdlLocation = "http://localhost:8989/sample?wsdl")
public class MessageSampleService
    extends Service
{

    private final static URL MESSAGESAMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGESAMPLESERVICE_EXCEPTION;
    private final static QName MESSAGESAMPLESERVICE_QNAME = new QName("http://app.cfn.com/", "MessageSampleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/sample?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGESAMPLESERVICE_WSDL_LOCATION = url;
        MESSAGESAMPLESERVICE_EXCEPTION = e;
    }

    public MessageSampleService() {
        super(__getWsdlLocation(), MESSAGESAMPLESERVICE_QNAME);
    }

    public MessageSampleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGESAMPLESERVICE_QNAME, features);
    }

    public MessageSampleService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGESAMPLESERVICE_QNAME);
    }

    public MessageSampleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGESAMPLESERVICE_QNAME, features);
    }

    public MessageSampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageSampleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessageSample
     */
    @WebEndpoint(name = "MessageSamplePort")
    public MessageSample getMessageSamplePort() {
        return super.getPort(new QName("http://app.cfn.com/", "MessageSamplePort"), MessageSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageSample
     */
    @WebEndpoint(name = "MessageSamplePort")
    public MessageSample getMessageSamplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://app.cfn.com/", "MessageSamplePort"), MessageSample.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGESAMPLESERVICE_EXCEPTION!= null) {
            throw MESSAGESAMPLESERVICE_EXCEPTION;
        }
        return MESSAGESAMPLESERVICE_WSDL_LOCATION;
    }

}
