
package com.cfn.app;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MessageSample", targetNamespace = "http://app.cfn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MessageSample {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showMsg", targetNamespace = "http://app.cfn.com/", className = "com.cfn.app.ShowMsg")
    @ResponseWrapper(localName = "showMsgResponse", targetNamespace = "http://app.cfn.com/", className = "com.cfn.app.ShowMsgResponse")
    @Action(input = "http://app.cfn.com/MessageSample/showMsgRequest", output = "http://app.cfn.com/MessageSample/showMsgResponse")
    public String showMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
