
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendSMSSoap", targetNamespace = "http://www.webserviceX.NET")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendSMSSoap {


    /**
     * Send unlimited free SMS to India - Maximum message size is 120 characters<br><br><b>Usage:</b>If your mobile number is 098XXXXXXXX ,Please enter as 98XXXXXXXX<br><b>Network Covered:</b> Airtel,Idea Cellular,Skycell ,RPG Cellular,Hutch,Celforce / Fascel,BPL Mobile,Escotel 
     * 
     * @param mobileNumber
     * @param fromEmailAddress
     * @param message
     * @return
     *     returns net.webservicex.SMSResult
     */
    @WebMethod(operationName = "SendSMSToIndia", action = "http://www.webserviceX.NET/SendSMSToIndia")
    @WebResult(name = "SendSMSToIndiaResult", targetNamespace = "http://www.webserviceX.NET")
    @RequestWrapper(localName = "SendSMSToIndia", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.SendSMSToIndia")
    @ResponseWrapper(localName = "SendSMSToIndiaResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.SendSMSToIndiaResponse")
    public SMSResult sendSMSToIndia(
        @WebParam(name = "MobileNumber", targetNamespace = "http://www.webserviceX.NET")
        String mobileNumber,
        @WebParam(name = "FromEmailAddress", targetNamespace = "http://www.webserviceX.NET")
        String fromEmailAddress,
        @WebParam(name = "Message", targetNamespace = "http://www.webserviceX.NET")
        String message);

}
